# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_service.proto\x12\x0b\x66ileservice\"0\n\x10ListFilesRequest\x12\x12\n\x05limit\x18\x01 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_limit\"C\n\x12SearchFilesRequest\x12\x0f\n\x07pattern\x18\x01 \x01(\t\x12\x12\n\x05limit\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_limit\"\x1f\n\nFilesReply\x12\x11\n\tfile_list\x18\x01 \x01(\t2\x9f\x01\n\x0b\x46ileService\x12\x45\n\tListFiles\x12\x1d.fileservice.ListFilesRequest\x1a\x17.fileservice.FilesReply\"\x00\x12I\n\x0bSearchFiles\x12\x1f.fileservice.SearchFilesRequest\x1a\x17.fileservice.FilesReply\"\x00\x42\x05\xa2\x02\x02\x46Sb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\242\002\002FS'
  _LISTFILESREQUEST._serialized_start=35
  _LISTFILESREQUEST._serialized_end=83
  _SEARCHFILESREQUEST._serialized_start=85
  _SEARCHFILESREQUEST._serialized_end=152
  _FILESREPLY._serialized_start=154
  _FILESREPLY._serialized_end=185
  _FILESERVICE._serialized_start=188
  _FILESERVICE._serialized_end=347
# @@protoc_insertion_point(module_scope)
