version: '3.1'
services:
  nfs:
    container_name: wp_nfs
    image: erichough/nfs-server:2.2.1
    privileged: true
    cap_add:
      - SYS_ADMIN
    ports:
      - "2049:2049"
    restart: always
    environment:
      NFS_EXPORT_0: "/mnt/wordpress                  *(rw,sync)"
    volumes:
      - ${WORDPRESS_DIR}:/mnt/wordpress
