version: '3.1'
services:
  nginx:
    container_name: dev_nginx
    image: nginx:1.23.1
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ${NGINX_CONFIG_DIR}/nginx.conf:/etc/nginx/nginx.conf
      - ${WORDPRESS_DIR}:/var/www/html/wordpress
      - ${LETSENCRYPT_DIR}:/etc/letsencrypt
