version: '3.1'
services:
  phpfpm:
    container_name: dev_fpm
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ${WORDPRESS_DIR}:/var/www/html/wordpress
