version: '3.1'
networks:
  wp_mysql:
    ipam:
      driver: default
      config:
        - subnet: "172.31.0.0/24"
          gateway: "172.31.0.1"

services:
  mysql:
    container_name: wp_mysql
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: secret
    networks:
      wp_mysql:
        ipv4_address: "172.31.0.2"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_SCRIPTS_DIR}:/opt/mysql/scripts
